import { useEffect, useState } from 'react';
import { CalendarDays, LogOut, Save, Plus, Trash2, Settings, Inbox } from 'lucide-react';

type EventItem={id:string;date:string;title:string;time?:string;description?:string;image_url?:string};
type Availability={date:string;status:'booked'|'club_event';label?:string};
type Enquiry={id:string;full_name:string;email:string;phone?:string;preferred_date?:string;function_type?:string;message?:string;created_at:string};
const defaultSettings:Record<string,string>={
  hero_eyebrow:'A hidden gem in Lovely Banks',hero_title:'Your local club. Your next celebration.',
  hero_description:'A welcoming community club and versatile function venue with a spacious hall, dance floor, full kitchen and staffed bar.',
  phone:'0452 077 627',email:'bookings@seaviewclubgeelong.com',instagram:'seaviewclubinc',
  address:'335 Bluestone Bridge Road, Lovely Banks VIC 3213, Australia',
  hero_image:'',hall_image:'',detail_image:''
};

export default function Admin(){
 const [auth,setAuth]=useState(false),[configured,setConfigured]=useState(true),[password,setPassword]=useState(''),[error,setError]=useState('');
 const [tab,setTab]=useState('calendar'),[availability,setAvailability]=useState<Availability[]>([]),[events,setEvents]=useState<EventItem[]>([]),[settings,setSettings]=useState(defaultSettings),[enquiries,setEnquiries]=useState<Enquiry[]>([]);
 const [date,setDate]=useState(''),[status,setStatus]=useState<'available'|'booked'|'club_event'>('booked'),[label,setLabel]=useState('');
 const [event,setEvent]=useState<EventItem>({id:'',date:'',title:'',time:'',description:'',image_url:''});
 const load=async()=>{const r=await fetch('/api/admin/data');if(r.ok){const d=await r.json();setAvailability(d.availability||[]);setEvents(d.events||[]);setSettings({...defaultSettings,...(d.settings||{})});setEnquiries(d.enquiries||[])}};
 useEffect(()=>{fetch('/api/admin/status').then(r=>r.json()).then(d=>{setConfigured(d.configured);setAuth(d.authenticated);if(d.authenticated)load()})},[]);
 const login=async(e:React.FormEvent)=>{e.preventDefault();setError('');const r=await fetch('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)return setError(d.error||'Login failed');setAuth(true);load()};
 const post=async(url:string,body:any)=>{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json()).error||'Save failed');await load()};
 if(!auth)return <div className="min-h-screen bg-ink flex items-center justify-center p-5"><form onSubmit={login} className="w-full max-w-md bg-white p-8"><p className="eyebrow">Seaview Club</p><h1 className="font-display text-4xl mt-3">Website Admin</h1>{!configured&&<p className="mt-5 bg-sand/30 p-4 text-sm">Admin code is installed. Complete the Cloudflare D1 and password setup to activate login.</p>}<label className="block mt-6">Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required /></label>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<button className="button button-navy mt-5 w-full">Sign in</button><a href="/" className="block text-center mt-5 text-sm underline">Back to website</a></form></div>;
 const tabs=[['calendar','Calendar',CalendarDays],['events','Events',Plus],['content','Website Content',Settings],['enquiries','Enquiries',Inbox]];
 return <div className="min-h-screen bg-cream text-ink"><header className="bg-ink text-white px-5 py-5"><div className="max-w-7xl mx-auto flex justify-between items-center"><div><p className="font-display text-2xl">SEAVIEW CLUB</p><p className="text-xs text-white/50">Website administration</p></div><button onClick={async()=>{await fetch('/api/admin/logout',{method:'POST'});location.reload()}} className="flex gap-2 items-center text-sm"><LogOut size={16}/>Sign out</button></div></header><div className="max-w-7xl mx-auto p-5 lg:p-8"><div className="flex gap-2 overflow-x-auto mb-8">{tabs.map(([id,name,Icon]:any)=><button key={id} onClick={()=>setTab(id)} className={`px-4 py-3 flex gap-2 items-center whitespace-nowrap ${tab===id?'bg-navy text-white':'bg-white'}`}><Icon size={16}/>{name}</button>)}</div>
 {tab==='calendar'&&<section className="grid lg:grid-cols-2 gap-6"><div className="bg-white p-6"><h2 className="font-display text-3xl">Update a date</h2><label className="block mt-5">Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="block mt-4">Status<select value={status} onChange={e=>setStatus(e.target.value as any)}><option value="available">Available</option><option value="booked">Booked</option><option value="club_event">Club event</option></select></label><label className="block mt-4">Public label (optional)<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="e.g. Rock 'n' Roll Social"/></label><button onClick={()=>post('/api/admin/availability',{date,status,label})} className="button button-navy mt-5"><Save size={15}/> Save date</button></div><div className="bg-white p-6"><h2 className="font-display text-3xl">Blocked / event dates</h2><div className="mt-5 space-y-2 max-h-[480px] overflow-auto">{availability.map(a=><div key={a.date} className="border p-3 flex justify-between"><div><b>{a.date}</b><p className="text-sm text-ink/60">{a.status}{a.label?' · '+a.label:''}</p></div><button onClick={()=>post('/api/admin/availability',{date:a.date,status:'available'})} className="text-sm underline">Make available</button></div>)}</div></div></section>}
 {tab==='events'&&<section className="grid lg:grid-cols-2 gap-6"><div className="bg-white p-6"><h2 className="font-display text-3xl">{event.id?'Edit event':'Add event'}</h2><label className="block mt-4">Title<input value={event.title} onChange={e=>setEvent({...event,title:e.target.value})}/></label><label className="block mt-4">Date<input type="date" value={event.date} onChange={e=>setEvent({...event,date:e.target.value})}/></label><label className="block mt-4">Time<input value={event.time||''} onChange={e=>setEvent({...event,time:e.target.value})} placeholder="7:30 PM"/></label><label className="block mt-4">Description<textarea rows={4} value={event.description||''} onChange={e=>setEvent({...event,description:e.target.value})}/></label><label className="block mt-4">Image URL<input value={event.image_url||''} onChange={e=>setEvent({...event,image_url:e.target.value})} placeholder="https://..."/></label><button onClick={async()=>{await post('/api/admin/events',event);setEvent({id:'',date:'',title:'',time:'',description:'',image_url:''})}} className="button button-navy mt-5"><Save size={15}/> Save event</button></div><div className="bg-white p-6"><h2 className="font-display text-3xl">Events</h2><div className="mt-5 space-y-3">{events.map(ev=><div key={ev.id} className="border p-4"><b>{ev.title}</b><p className="text-sm text-ink/60">{ev.date} · {ev.time||'Time TBC'}</p><div className="flex gap-4 mt-3"><button onClick={()=>setEvent(ev)} className="text-sm underline">Edit</button><button onClick={async()=>{await fetch('/api/admin/events/'+encodeURIComponent(ev.id),{method:'DELETE'});load()}} className="text-sm text-red-700 flex gap-1"><Trash2 size={14}/>Delete</button></div></div>)}</div></div></section>}
 {tab==='content'&&<section className="bg-white p-6 max-w-4xl"><h2 className="font-display text-3xl">Website content</h2><p className="text-sm text-ink/60 mt-2">Edit the main public-facing details. Image URLs can be replaced now; direct image uploads will use R2 in the next step.</p><div className="grid md:grid-cols-2 gap-4 mt-6">{Object.entries(settings).map(([k,v])=><label key={k} className={k.includes('description')||k==='address'?'md:col-span-2':''}>{k.replaceAll('_',' ')}{k.includes('description')||k==='address'?<textarea rows={3} value={v} onChange={e=>setSettings({...settings,[k]:e.target.value})}/>:<input value={v} onChange={e=>setSettings({...settings,[k]:e.target.value})}/>}</label>)}</div><button onClick={()=>post('/api/admin/settings',{settings})} className="button button-navy mt-6"><Save size={15}/> Save website content</button></section>}
 {tab==='enquiries'&&<section className="bg-white p-6"><h2 className="font-display text-3xl">Function enquiries</h2><div className="mt-5 grid gap-3">{enquiries.length?enquiries.map(q=><article key={q.id} className="border p-4"><div className="flex flex-wrap justify-between gap-2"><b>{q.full_name}</b><span className="text-xs text-ink/50">{q.created_at}</span></div><p className="text-sm mt-1">{q.email} {q.phone?' · '+q.phone:''}</p><p className="text-sm mt-2 text-ink/60">{q.preferred_date||'No date'} {q.function_type?' · '+q.function_type:''}</p>{q.message&&<p className="mt-3 text-sm">{q.message}</p>}</article>):<p>No enquiries yet.</p>}</div></section>}
 </div></div>
}
